[all]
# Define your target hosts here
# Example:
# ubuntu-host ansible_host=192.168.1.100 ansible_user=ubuntu

[docker_servers]
# Hosts to install Docker on
ubuntu-server ansible_host=192.168.0.100 ansible_user=debjoti
